version: '3.5'

services:
  postgres:
    restart: unless-stopped
    # no exposal via traefik, use pgadmin to maintain
  
  pgadmin:
#    ports:  # exposal only via traefik
#      - "${PGADMIN_PORT:-5050}:80"
    labels:
      - traefik.http.routers.pgadmin.entrypoints=https-ep
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.astroloba.net`)
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=le

      # enable basic auth as defined in traefik's docker compose file
      - traefik.http.routers.pgadmin.middlewares=my-basic-auth