version: '3.5'

services:
  postgres:
    restart: unless-stopped
    # no exposal via traefik, use pgadmin to maintain
#    ports:
#      - "5432:5432"
#    labels:
#      - traefik.enable=true
#      - traefik.docker.network=traefik-public
#      - traefik.http.routers.postgres-db-insecure.entrypoints=http-ep
#      - traefik.http.routers.postgres-db-insecure.rule=Host(`postgres-db.localhost`)

  
  pgadmin:
#    ports:  # exposal only via traefik
#      - "${PGADMIN_PORT:-5050}:80"
    labels:
      - traefik.http.routers.pgadmin-insecure.entrypoints=http-ep
      - traefik.http.routers.pgadmin-insecure.rule=Host(`pgadmin.localhost`)