version: '3.5'

services:
  postgres:
    container_name: postgres-container
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${INITIAL_POSTGRES_USER:?err}  # only for initial setup
      POSTGRES_PASSWORD: ${INITIAL_POSTGRES_PASS:?err}  # only for initial setup
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - traefik-public

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:latest
    volumes:
       - pgadmin:/var/lib/pgadmin
    networks:
      - traefik-public
    restart: unless-stopped
    labels:
      # enable traefik for this specific service
      - traefik.enable=true
      # use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public

networks:
  # use the previously created public network "traefik-public"
  # create at first time via "docker network create traefik-public"
  traefik-public:
    external: true

volumes:
    postgres:
    pgadmin: